apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      version: 9.2.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 60m
  interval: 30m
  timeout: 20m
  install:
    remediation:
      retries: -1
  # Add this to force Flux to check the secret's version
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # See https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml
  values:

    phpClientHttpsFix:
      enabled: true
    env:
      PHP_MEMORY_LIMIT: 256M

    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:nextcloud
        hajimari.io/info: File and Calendar server
        hajimari.io/group: tools
        nginx.ingress.kubernetes.io/enable-global-auth: "false"

        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false
      auth:
        existingSecret: nextcloud-helm-values
        existingSecretPasswordKey: REDIS_PASSWORD
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db-app
        usernameKey: user
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    cronjob:
      enabled: true
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      sidecar:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi

    nextcloud:
      host: ${NEXTCLOUD_OVERRIDE_HOST}
      trustedDomains:
        - ${NEXTCLOUD_OVERRIDE_HOST}
        - nextcloud.pub.${CLUSTER_DOMAIN}
        - nextcloud.home.${CLUSTER_DOMAIN}
      extraEnv:
        - name: TRUSTED_PROXIES
          value: '${NETWORK_K8S_CLUSTER_CIDR}'
        - name: FORWARDED_FOR_HEADERS
          value: "HTTP_X_FORWARDED_FOR"
        - name: OVERWRITEHOST
          value: "${NEXTCLOUD_OVERRIDE_HOST}"
        - name: OVERWRITECLIURL
          value: "https://${NEXTCLOUD_OVERRIDE_HOST}"
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
          default_phone_region = DE
      configs:
        gitops.config.php: |-
          <?php
          $CONFIG = array (
            'appstoreenabled' => true,
            #'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
            'mail_domain' => '${CLUSTER_DOMAIN}',
          );
        
        #Circumvention for client freezes - https://github.com/nextcloud/desktop/issues/6990
        bulkupload.config.php: |-
          <?php
          $CONFIG = array (
            'bulkupload.enabled' => false,
          );

        oidc.config.php: |-
          <?php
          $CONFIG = array (
            'allow_local_remote_servers' => true,
            'shareapi_restrict_user_enumeration_to_group' => true,
          );
        
        others.config.php: |-
          <?php
          $CONFIG = array (
            'maintenance_window_start' => 1,
          );
        
      mail:
        enabled: true
        fromAddress: nextcloud
        domain: ${CLUSTER_DOMAIN}
        smtp:
          host: ${CLUSTER_MAIL_SERVER}
          secure:
          port: ${CLUSTER_MAIL_SERVER_PORT}
          authtype:
          name:
          password:
      
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      extraVolumes:
      - name: nfs-video
        nfs:
          server: "${NFS_SERVER}"
          path: "${NFS_VIDEO}"
      - name: nfs-software
        nfs:
          server: "${NFS_SERVER}"
          path: "${NFS_SOFTWARE}"
      - name: nfs-music
        nfs:
          server: "${NFS_SERVER}"
          path: "${NFS_MUSIC}"
      - name: nfs-downloads
        nfs:
          server: "${NFS_SERVER}"
          path: "${NFS_DOWNLOADS}"
      - name: esphome
        persistentVolumeClaim:
          claimName: esphome-pvc
      extraVolumeMounts:
      - name: nfs-video
        mountPath: "/video"
      - name: nfs-software
        mountPath: "/software"
      # - name: esphome
      #   subPath: devices
      #   mountPath: "/software/3D-printer/projects/Electronica/esphome_devices"
      - name: nfs-music
        mountPath: "/music"
      - name: nfs-downloads
        mountPath: "/downloads"

      hooks:
        post-upgrade: |
          cd /var/www/html
          ./occ upgrade
          ./occ db:add-missing-indices

        before-starting: |
          #!/bin/bash
          set -exu # Remove the -u if you encounter issues booting

          cd /var/www/html

          # Upgrade
          ./occ upgrade                                || /bin/true
          ./occ maintenance:mode --off                 || /bin/true
          ./occ app:update --all                       || /bin/true
          ./occ db:add-missing-indices                 || /bin/true
          ./occ maintenance:repair --include-expensive || /bin/true

          # SSO
          test -d custom_apps/user_oidc ||  ./occ app:install user_oidc
          ./occ user_oidc:provider sso \
            --clientid="${NEXTCLOUD_OIDC_CLIENT_ID}" \
            --clientsecret="${NEXTCLOUD_OIDC_CLIENT_SECRET}" \
            --discoveryuri="${NEXTCLOUD_OIDC_URL}" \
            --unique-uid=0 \
            --group-provisioning=1 \
            --group-whitelist-regex='${NEXTCLOUD_OIDC_GROUPS_WHITELISTED_REGEX}' \
            --group-restrict-login-to-whitelist=1 \
            --mapping-groups=groups \
            --claims-mapping='{"email":"email","name":"name"}'
          ./occ config:app:set --value=0 user_oidc allow_multiple_user_backends # Only login with SSO
          
          # notify_push
          test -d custom_apps/notify_push ||  ./occ app:install notify_push
          ./occ notify_push:setup https://${NEXTCLOUD_OVERRIDE_HOST:=${TENANT_DOMAIN}}/push || echo "Could not setup notify_push"

          # collabora
          test -d custom_apps/richdocuments ||  ./occ app:install richdocuments
          ./occ config:app:set richdocuments wopi_url --value https://${COLLABORA_HOST}
          ./occ richdocuments:activate-config

          # # integration_openai
          # test -d custom_apps/integration_openai ||  ./occ app:install integration_openai
          # ./occ config:app:set integration_openai service_name --value "kvant"
          # ./occ config:app:set integration_openai url          --value "${KVANT_LLM_URL}"
          # ./occ config:app:set integration_openai api_key      --value "${KVANT_LLM_APIKEY}"
          # ./occ config:app:set integration_openai chunk_size   --value 100000

          # Other installed apps
          APPS=(
            announcementcenter
            assistant
            call_summary_bot
            context_chat
            deck                 # Kanban for small projects
            drawio
            files_mindmap
            forms
            groupfolders
            integration_jira
            notes
            #spreed               # Talk
            whiteboard
          )
          for app in $${APPS[@]}; do
            test -d custom_apps/$app ||  ./occ app:install $app
          done

          # Theme
          ./occ theming:config name                 "Casa Nextcloud"
          ./occ theming:config url                  "${NEXTCLOUD_OVERRIDE_HOST:=${TENANT_DOMAIN}}"
          # ./occ theming:config imprintUrl           "https://kvant.cloud/en/terms"
          # ./occ theming:config privacyUrl           "https://kvant.cloud/en/privacy-policy"
          # ./occ theming:config slogan               "The Swiss Sovereign Cloud: Your Data, Our Territory"
          # ./occ theming:config primary_color        "#8FEAFF"
          # ./occ theming:config disable-user-theming --reset
          # ./occ theming:config background           "/themeFiles/background.png"
          # ./occ theming:config logo                 "/themeFiles/kvant_logo.png"
          # ./occ theming:config logoheader           "/themeFiles/kvant_logo.png"
          ./occ theming:config favicon              --reset

          # start a task worker
          nohup ./occ background-job:worker 'OC\TaskProcessing\SynchronousBackgroundJob' &

          # # talk
          # ./occ talk:signaling:delete https://talk-${TENANT_DOMAIN}
          # ./occ talk:signaling:add --verify https://talk-${TENANT_DOMAIN} ${SIGNALING_SECRET}
          # ./occ talk:turn:delete turn nextcloud-talk-turn.${TENANT_NAMESPACE}.${CLUSTER_DOMAIN} udp,tcp
          # ./occ talk:turn:add --secret ${TURN_SECRET} turn nextcloud-talk-turn.${TENANT_NAMESPACE}.${CLUSTER_DOMAIN} udp,tcp

      # extraInitContainers:
      # - name: fix-permissions
      #   image: docker-mirror.pub.basel.kvant.cloud/library/nextcloud:32.0.12@sha256:90fdc9f99fab6f8dcfb16f6010a2a615775f01ed8e9265fa10beed6b2f10cbae
      #   volumeMounts:
      #     - name: nextcloud-main
      #       mountPath: /var/www/html
      #       subPath: html
      #   command:
      #   - /bin/sh
      #   - -c
      #   - >-
      #     cd /var/www/html;
      #     mkdir -p config;
      #     chown www-data:www-data *;
      #     ls -l
      #   resources:
      #     limits:
      #       cpu: 10m
      #       memory: 128Mi
      #     requests:
      #       cpu: 10m
      #       memory: 128Mi
    

    collabora:
      enabled: true
      autoscaling:
        enabled: true
        minReplicas: 1
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 80
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      serviceAccount:
        create: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
      collabora:
        extra_params: --o:ssl.termination=true --o:ssl.enable=false --o:logging.disable_server_audit=true --o:security.mount_jail_tree=false
      ingress:
        enabled: true
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
        hosts:
          - host: ${COLLABORA_HOST}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
        - hosts:
          - ${COLLABORA_HOST}

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
        
    persistence:
      enabled: true
      existingClaim: nfs-nextcloud
    
    rbac:
      enabled: true
      serviceaccount:
        create: true
        name: nextcloud
