okd:
  client: https://github.com/okd-project/okd/releases/download/4.21.0-okd-scos.9/openshift-client-linux-4.21.0-okd-scos.9.tar.gz
  install: https://github.com/okd-project/okd/releases/download/4.21.0-okd-scos.9/openshift-install-linux-4.21.0-okd-scos.9.tar.gz