apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    # renovate: depName=fluxcd/flux2 datasource=github-releases
    version: "2.9.1"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
    size: small
  sync:
    name: cluster-repository
    kind: GitRepository
    url: "https://github.com/angelnu/k8s-gitops.git"
    ref: "refs/tags/production"
    path: "clusters/prod/config"
    #pullSecret: "flux-system"
  
  kustomize:
    patches:
      # Allow accessing cluster-repository from other NSs
      - target:
          kind: Deployment
          name: helm-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-            
            value: --no-cross-namespace-refs=false

      # Enable In-Memory Kustomize Builds
      - target:
          kind: Deployment
          name: kustomize-controller
        patch: |
          - op: replace
            path: /spec/template/spec/volumes/0
            value:
              name: temp
              emptyDir:
                medium: Memory
  