# Passwords are stored in the clear here on purpose: the gen-passwd
# initContainer hashes them with `mosquitto_passwd -U` at pod startup.
# Adding a user is one more line; rotating one is an edit + reconcile.
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
stringData:
    passwd: ENC[AES256_GCM,data:+UWUDD/bjcg4GxknaQKjFmk3zJWDLXeCCBwhX3Lv3jiwRvh8HeR6G+LOUIW5ByefNm1vKZ7uMxIVjcW1bwjmxpWUuAvadA==,iv:ITZz0ST4o6mQqEqgsZy6ZiTRvrzzLr+S5z+nfKyevJg=,tag:+O2lqLG354bKP+mWuNSqtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OCtLWXh5OGhuQkZtbGk1
            OGJvVTZXNVpyV2JwQjl5YStNNC9TTHQ3TmtnCkVuMms2YlFXYngwdEtRM2t5VmVv
            TURvdFZTWEt2UlArNW0vSzRCVFVKZWsKLS0tIFR2bnZUamU1WWlQUHVVWklrdnIv
            RVdPWGdMcURtdC8yb1MxaXZrdzhWNjgKcR/eiX+XMOKW6MOg9FdFrdEc7rzLzzJ7
            vxA+cPvEgbXmg/HDTwnO7i+dVDsiFbjaqrivi3aK/5SRriXhAtMbcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU1JURFRCTHVCVm9DR1Zy
            RXBBaHdPZlpyK0xMQ2ZxVC9icks3R0t6R0ZFCldNRGNjWmtuOEdtaTFIQWdVVGNO
            ZENWM0J1WVFwNXFvV0ZTZ1hSeW1YVTAKLS0tIEs2RGoyd3lxL2M3V1creE9PU2FR
            VFk5dWJVaUhoa2xaNmppSlMxL3NzcWcKKBEvzxMOjtvUh0Lv6c3t6zzsbyRR3pBr
            KgvZIb0oVDtk7/wh6mvF7Yg665zHu23vj4/1UjaxDVzIBty4o4YVSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYU0vbzlUOGZlTFVaL2FS
            N1F6cGphYWdsczBZNVBXblo4R1JURUxGYVRRCnc4ei9mSFZjUEtpaWJZWVBscVZR
            STBoUWVCMks5YlFzdjJGYUhMVFZEN1kKLS0tIHBPQUdtMWNyR1Z6dlRwZEk5YWVD
            ajdjUG9aNkpRR254aEJ0dlppdGt1a0kKjS6ESmFgQ1dlB5IPe+pSfpOSJO5Mg3oL
            EClu29pj8nZctF1VZ7EDageP7lAU3OpcMXc+tx39NLlLBYaoFa1BMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZUtROEVmeStrd2lvQnll
            Z1ArSDM5N2w3bUo3aGdWSUdkYVRZVmhwcndjCjBYeTJzTUN4SEtVdUJNcDh0dGFV
            ME5WdHNSa3BDdWhueHFRcnphWGIvbDQKLS0tIHFHNXo2RmhSY3RqNG02cURuT0xY
            SysrM2dVdkpVZWFZMnpRcE4xZjdnc3MKRQg3ByqJ2jPW1Un+Y2F9DqT9jL83ula4
            LfiqhJ2q4lSP9nacfOA9W9M/IxLRx/aYhrJowBMk47nDWZTKadqG4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-09T16:25:10Z"
    mac: ENC[AES256_GCM,data:KE533UUHp/rFEEJpFMsmWgPamFH8DO4U2nDTdA1/GLY/ie01DxViGQtQlusBhAO2L1cwJjQ/zyeWoXS6Q5Blg3ukx/wII5H8ufmcBXg9FFNCuyxrLqIgTfFfXK1BhGa6uqM0O5zJ8aAkfQwow5RNHubiGGTIfEycAjFA2Xb2jrQ=,iv:48tUXWMWP/I7P9Z90sCV+nb1P4ZMaxYlu1ZCYTFzdLc=,tag:U8VZyoRwn8fj3kzS7vczkw==,type:str]
    version: 3.13.3
