apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-whiteboard-secret
  #Password generate with https://generate.plus/en/base64
stringData:
  JWT_SECRET_KEY: ENC[AES256_GCM,data:6BD8Jdqfh9eHm1tuH3ZgrvL6Z/gIuWLAiUZiD4oSu03CyTTdtGAXZjO0+Gg=,iv:fCC49WycmtfUtIYDjYz1yCDWyDBeJMuaIZH47656Raw=,tag:Yjt2sAF7kH2J35M9SPg7hw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFlVNXlTS3pGVVd0TDFp
        d29ubWF0OC9ISHNJenBPODg2RjVRV1A1K0VFClRJN1lZdU9tRUlYeHNLU0xXVTl1
        MGVhSnZwd3JkOFJidEF4empHeUxEODgKLS0tIERKNWd5NzhITHVqRWxhZU1lT3hq
        dEpFbUxNazZEbkk3QXRXR0ZodVIyNmsKlzK5WY0qJabOhcrNkCh0JIez+NyMxuGo
        LsSLKJozqpOcHwheBwZi1S3EIjIpkpWFwMLGSplgzrGYUA4jeTXafA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVjFpOTJNZXFsbCtSZW00
        cHZhTDNLZ0VSZjUvYlIvOVFwaWROSkg5dmlrCnd0emZoWnFaWVQzenV3cStVTStn
        TldDdW1HRkkrbFdFTlo0VFBHNGhvQ00KLS0tIElKdW1ERUZpN1RVWTFvUWZ3TUd2
        VTJPK2h2eklPZWIyUjE0TzV4Z3VsdUUK8pQO2by6u35BWRtcRU4DMx7Nx7yB+lvf
        8E/CnVk70MTmMPa7Zoz6rAug3S/O9rcKTcfhDkgxTLLgcHrlfsWEGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM0U0MXU1N2VXRU94enpJ
        cHlTMCt4bmFUS0EvRWpxV0lhMUd6SXpoMFZNCmZSU1ZoaEM5S2lLSzNZTHNBUFBr
        eXlidmNDWEdDeU9XbWlNMXVSallBc2cKLS0tIHFHMkhWQThoQWRBTEdzMWxsQy9h
        RXNlZk54RzRhTlhDNzQ5c0llcTJ3M3MK/qdveWa/C6pT0ZT+mQbqI9KV3IKDuTFy
        /Qmml66926P5ty73wAm33JSyXUAJJtXYEK/TAZ3hvHrb/CGhvR5oCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc3hhZE5CcGJVNXgzNURH
        YlZaQy9BT0Fud3hEOFZzcXFiMmVqNlZFbzMwCkltYSthbXdKd2xlV0FPZVdKeHBv
        aWV1QzcvZHpTRE5JQW1iUWI3Z09vd1UKLS0tIDhsZGpoQ2p3d2prcmF0bytFV1B5
        aTNQK09NWHlFM1RUNjFiRU1ta3RXTXcKMO5LXkokTA1S4afsKwYW/WYR4hS3HWIs
        Tv5M7F0Y92IwEM8EK4LqSN0cbe1UFg48/MY4Cz4LlgeU7uP39NBIFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T21:00:33Z"
  mac: ENC[AES256_GCM,data:uUkmfAnza/33NVSwgSK2EHkHlg1JB7wMnn3dnUgP6op0ds+LFe2J03xMEwKA8v1Ntn6o1Ojm8kv28fy5ZUnQuherE67knGjdUItLndKLkuBl6F9myPtwxAk6nChil/1amXEl3IbHQVJWW6wqLKrQBkcgVwIE3L/G7Uwt5/ZZLVM=,iv:z7ryLjd8jVbW+ThHN3D9P6/YDSSujpeClt0idjJpuPY=,tag:1YKdPivfGcYS1FEUPSsjmw==,type:str]
  version: 3.13.3
