apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:uxO5JAYLtp8t/mkLaJZ93KEWlLtUMdQYHh2owp9D06heoXwYfc6PfVYRApgHsuu8pdY5637+N5ulcwjR6xewsNldHQI+uWAXKJV2BS9wa1C9H7FxN7vpLoM6Aj+o6bwGIWBpHk9faZwupUgg8VdFvJYbjNwlTIedEaODscwitMf83jgh1/rc+hsQsl50hW8PpnonrsIU4jPWdw31lFoWG1JMdIb0dqHaSL+BhdGKZkyRAoRkjWgP1P/BtN43GAknAJKiM0DqxZ6A5iCYpc1xX3axYoAwHNP5wVacESGJi0rbX694f4SXuG2KRKA9RrV9,iv:86K1QozrqAXxcysDHMx2MBUWWj+U0YuPny/k2PrfLxQ=,tag:8QnDMmX2UeR6IaWzisRqDg==,type:str]
kind: Secret
metadata:
  name: forgejo-registry
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcVUwUU9IUGw5blBNMnpR
        YmI4NEFUZ05qZDVvLytoUitYaU91QmZpRGxjClRHaWgzWndmRFAvZjJaUGNIRi9T
        YVVRR2w2MHFzbm50U3lFVVk1YVArNWcKLS0tIFNORDlDVFg4TDR0MFJmSmZZSnZh
        d2g5Qi9IQlpJVmo2SzV5VU82L0VDaUkKfDWEjLHwuL+nDZ7diN3wC2Dx8MYkNAJv
        9JrGyXwLndmAn6CRPF8+RoqbFzspSMfXjhQMrEzLgsCdz5fwna1how==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bTA3aFZLbGxQRlhId2sz
        bm5rOG5aSm1SQmhqemJmaGMrREhiZ1NxMXdnCnljNE1kYmFBZFRPdEFpc0owdGIz
        NCtJRmtkVnRYc2V6VWxkWlRKd3BQRWsKLS0tIFNyT0pjeHVFdTVEUmRSb2g4Yjd2
        dk1zRTRzRUFpbzB2ZldBYWFTZG9TU0EKMFdLdA2OjFR9a6PlQpHW0f3NN7kwh8RA
        kuSmnnAGWt2w16VS4O6JDsKLjlFemtmL2oW44koiVPrzO9ui3/Hj8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQ25RVjBTbGphUnlUMG0y
        TkQ3Q3E4T05xd3VKVFdHQTBQa24va3RyUTBVClF3MVBJSEdLTElGV1l1WGJLMXdj
        TFlQZHE5UmdiUW00bWVnbDk1aHUvSmcKLS0tIGpRYnJlVnJVcFRpQXVpTzBmMVI5
        bWJ4cm9tWkM0TlpJWmlhMXlUMGVoZVUKuSjbKef6nQRP3eom8xucOKMOpMEHe6CS
        T4PIoOT9kunAAVYmRGfGDH5+cCoEMljoKDXmUSDBaDv/8I4UJwiC6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN1hMUmFQK2FqS0FEWVlw
        Y2t6S2hoR2xFWmZqV3k5VWt5ZmEyMTBiNGpNClc3RmFteEEvUHFGSHZsdnhOczhH
        UWI5UjYrUDdlOVowWEpzcXI4MU1hVTQKLS0tIHFFd2VLUm1MeGVydkVjOG5HUit0
        N2RIYy81UlVpUkVJRjRUNGtsMk1Pbk0KjY1iMTXM5IJoGpi3yaXTWT/boBAPi0eX
        lrSkzcDUx475KLI8Z7/uSfXZDvXhGpg+V/YCaNOnPoDBICVvlUEi0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T19:39:49Z"
  mac: ENC[AES256_GCM,data:eNEkS4EyrsXjTS0xw1+4mVKomKdbBmgxGJD0F09QecdbHSj7G0PLeGXLvs55Hy5aYY6Q/RpZN9tRvulr0vJNXDr0a5IQgdatVZH2e9Eq1QaX2voHET6zjdKpa35X02wk0GmqwiG+d6w4f6Ym3Y2JDBHFM0KmQJ8lYTgOm/figj8=,iv:Q3jobp6ntx5akJYfRbLWWAnO6F45sEJ9reYTgC3lv/4=,tag:YwYmHhBmCO3wff50DiFegw==,type:str]
  version: 3.13.3
