apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-postgres
provisioner: openebs.io/local
parameters:
  storageType: "hostpath" # Add this line
  basePath: "/var/openebs/local" # Ensure this matches your host directory
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete