apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-talk-signaling-secret
  #Password generate with https://generate.plus/en/base64
stringData:
  SIGNALING_SECRET: ENC[AES256_GCM,data:/9zI+jvDast2NoGRnZyFY5nPD7dnJs1L93XoLrISNpptGvcGT0hFQz8lfoAIuzHPuUaSROIKN0qUqZWpr72QwA==,iv:dIGavNuqE3PyfDstmJDLwa4JKDfYERadk/UBCW6nPZY=,tag:xZdSjcSa+HXcRIAezWrDYw==,type:str]
  server.conf: ENC[AES256_GCM,data:30m6OcECF0Lra5ThSzhahoiMkaa1iZ+EtxFbQPozoDZ3SyVxGEw8JBRKF96oViOZHf1ASxwvxqiWLURKaHQZ/tZJEPS4FxqmySwn6CBnt9ZGTcd8n111e1+nu9od6VmhVIdlJqfErBSCjav6EIIjqdLgCLVN6fBxKewXCVfe/cvmp1FT1B7eV3Tx9egvjRrWxP+e7ZPox7FHR3W7yijsYRFkRVyWL/Q8MpoBX0hwO9rWp1OJWqwg3dc0wQXbKIAfc4GT5jjBMGUABtcmeTDCnwov5qH0VY67aw2rJV5cppP0XyEewID9oU4r04zXzOzn4syocUlGjTHmiQas4AVsJMxVW4BUXbAyuCFVI0ySycwyBnO/SW2mfODzKVPYSUibDlLXPO6al+wAgbtIPxQcHEYeOuuhvKXyyOt1cr/DkYruS/N0CXNipncFKkIeD0j/rXImAicQDXlmxg73haqwFnDardpb80JJXeqVFF/H0VyZEyAKus2F24qeDAWG8xk2BpbG/9fU/dn1jKP5LTc6QgC5ZSPS2FMXSgZEN8lJx5QpDQq+Ao6ATTdCVlf9DX1TlbmvNXtEwHc/,iv:QS8822ZDatDV5qOQN0jczkxvGSW7XUoF3wAClO0SAR0=,tag:89MQCWHqaCtkZur9LdjMkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaUNJbWlsbkI0RjRiTDRi
        ak9Ob2tvQmRKNDZUaEhjYlhaT1pWalFZVmxNCjVCWVlidVpEaFdCclRwNkFrU0R4
        YU5zb1hjT2M4dEZHTjJDSDVtMXk4bGsKLS0tIEhkdCtKckNCbE1zUnBESlV0Z2Zs
        TEc4SG8yNm80S0hOOVVUOGowSEpCSDQKYLbZtNEL5dmSE36RH3DSWVU473bZyPFP
        idFsg7Mc3YDNlJ2/GXkiAdB6iiase5SIJgKKtLSSTsVw6mQHeXUfdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSHNBcjNzZGh4OVhwRWoy
        ZkdzNFFORjUwQzluaEVJYTNzR3FNUk9mK0ZjClhQS2NGbmtiVG1nQ0dYbmpTT0VI
        TGtHV3RKQk5OSmxjK0xDSVB3QkJKb0EKLS0tIFl4YnMzTnYvTms2QjdhRGJRVjho
        djNPZjVrY2xFRDVvckRQVkpNSzdDLzAKVLKH9G2i/RhxEPxWgdmEafhsIfF+tVxU
        C8/Cg7VZstP0oaIsR/9mlUYDvYfx4qV2jSNqSDHYVqsIRMlR0hi0WA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSm1XQXE4WDhzV1Q3ZCtn
        M1l2YzBFRE5CQkZvK3RtVUFIa0N1dmR4Tkc0CmwyWkx2ZzRHOEMyQnlZLytlMW93
        K3NRVUJWUzFqZWRxZzVIN0VWTjBjWkEKLS0tIEFSQnlsMHd3VXBWbnNRQ1JhV05F
        U1JsSXRZR0ljdW5aejA5aGRJZFR2NlkKQ/xBWxvs83LPfomIyEgD/7oEE3UejtJ6
        N7t5s/qCsj8UaMMcFrF5yQtJkYBR2sr7kQMWfH7EkArbx7ncNNKrvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUmJkZnVPdGJNWEE5L21U
        K0ppc2NzSXgwU2hKN0hXS1FWQUNaWUpvU0U0CitYMDFseHFoU1BSY0tUeVlKd1pS
        M3JrQnpZQ21Nb2VYZ2lZYmJSY2s1SDAKLS0tIFBueWhucVFjWEZJTXlHeVlUWEdN
        NkVReUtJYi9vQ25YZTZaRE81WjhIeDgKn3vO9o82Hw3pq1CLItro8n+jLJtlUjh3
        bAeN5Y7madKNCH4fk21z4T4bGJ1chBmNH355qDJes6BqY1ZxQ0SdfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T21:57:52Z"
  mac: ENC[AES256_GCM,data:wXAFV/NlWpj/VbBjj/sn18XZVusuApk9x8d/BJaXXmpEkUcuK8lRjefFXRXQ4NW2uCJPVsvF59hj2W58h7s+uqB7XZ8QVrB9e2R2hlpU4qZiQFTvWDkdFiwwLL6ocSoIpRmMruapO6yVE5OrSC01U0Z/85qFUllASmyQbWD39xk=,iv:HyCac7XswDzhDE+0lU9LGNr0tXk1dgG88fks4HhB52Q=,tag:KhlmROfrkObln+RrL5kCKg==,type:str]
  version: 3.13.3
