---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: paperless
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputs:
    - name: casa
      ignore_dates: “1978-09-19,1979-06-12,2010-2-8,2011-11-15”
      ocr_language: deu
      hostname: paperless.pub.${CLUSTER_DOMAIN}
      hajimari_group: documents
      auth_request_set: $required_usernames 'angel|mireille'
    - name: edu
      ignore_dates: “1984-09-09”
      ocr_language: spa
      hostname: paperless-edu.pub.${CLUSTER_DOMAIN}
      hajimari_group: spain
      auth_request_set: $required_usernames 'eduardo'
    - name: javi
      ignore_dates: “1984-09-09”
      ocr_language: deu
      hostname: paperless-javi.pub.${CLUSTER_DOMAIN}
      hajimari_group: documents
      auth_request_set: $required_usernames 'javier'
    - name: madrid
      ignore_dates: “1984-09-09”
      ocr_language: spa
      hostname: paperless-madrid.pub.${CLUSTER_DOMAIN}
      hajimari_group: spain
      auth_request_set: $required_groups 'madrid'
    - name: mireille-work
      ignore_dates: “”
      ocr_language: eng
      hostname: paperless-mireille-work.pub.${CLUSTER_DOMAIN}
      hajimari_group: documents
      auth_request_set: $required_usernames 'mireille'
    - name: recipes
      ignore_dates: “”
      ocr_language: deu
      hostname: paperless-recipes.pub.${CLUSTER_DOMAIN}
      hajimari_group: documents
      auth_request_set: $required_usernames 'anunez|mireille'
  resources:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: paperless-<< inputs.name >>
        namespace: << inputs.provider.namespace >>
      spec:
        chart:
          spec:
            chart: app-template
            version: 5.0.1
            interval: 60m
            sourceRef:
              kind: HelmRepository
              name: bjw-s
              namespace: flux-system
        interval: 30m
        timeout: 20m
        install:
          remediation:
            retries: -1
        # Add this to force Flux to check the secret's version
        upgrade:
          cleanupOnFail: true
          remediation:
            strategy: rollback
            retries: 3
        # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
        values:
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: ghcr.io/paperless-ngx/paperless-ngx
                    tag: 2.20.15 # renovate: depName=ghcr.io/paperless-ngx/paperless-ngx datasource=docker
                  
                  env:
                    PAPERLESS_OCR_LANGUAGE: << inputs.ocr_language >>
                    PAPERLESS_TIME_ZONE: "Europe/Berlin"
                    PAPERLESS_CONSUMER_POLLING: "60"
                    #PAPERLESS_CONSUMER_RECURSIVE: "true"
                    #PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
                    PAPERLESS_REDIS: redis://localhost:6379
                    PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
                    PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME
                    PAPERLESS_LOGOUT_REDIRECT_URL: https://authentik.pub.${CLUSTER_DOMAIN}/outpost.goauthentik.io/sign_out
                    PAPERLESS_IGNORE_DATES: << inputs.ignore_dates >>
                    PAPERLESS_URL: https://<< inputs.hostname >>
                broker:
                  image:
                    repository: docker.io/library/redis
                    tag: 8.8@sha256:0a972391db0b24ec336e35d1bc98b237237e26f82bf5120cf2f6b1688d1df973 # renovate: depName=docker.io/library/redis datasource=docker

          persistence:
            data:
              enabled: true
              type: custom
              globalMounts:
              - path: /usr/src/paperless/data-old
                readOnly: false
              volumeSpec:
                nfs:
                  server: "${NFS_SERVER}"
                  path: "${NFS_KUBERNETES}/paperless/<< inputs.name >>/data"                  
            data-new:
              enabled: true
              type: persistentVolumeClaim
              existingClaim: paperless-pvc
              globalMounts:
              - path: /usr/src/paperless/data
                subPath: << inputs.name >>
            media:
              enabled: true
              type: custom
              globalMounts:
              - path: /usr/src/paperless/media
                readOnly: false
              volumeSpec:
                nfs:
                  server: "${NFS_SERVER}"
                  path: "${NFS_KUBERNETES}/paperless/<< inputs.name >>/media"
            consume:
              enabled: true
              type: custom
              globalMounts:
              - path: /usr/src/paperless/consume
                readOnly: false
              volumeSpec:
                nfs:
                  server: "${NFS_SERVER}"
                  path: "${NFS_DOWNLOADS}/scanner/<< inputs.name >>"
            export:
              enabled: true
              type: custom
              globalMounts:
              - path: /usr/src/paperless/export
                readOnly: false
              volumeSpec:
                nfs:
                  server: "${NFS_SERVER}"
                  path: "${NFS_KUBERNETES}/paperless/<< inputs.name >>/export"
    
          serviceAccount:
            default:
              enabled: true
          rbac:
            bindings:
              default:
                type: RoleBinding
                roleRef:
                  name: system:openshift:scc:hostmount-anyuid-v2
                  kind: ClusterRole
                subjects:
                  - identifier: default

          service:
            main:
              controller: main
              ports:
                http:
                  port: 8000

          ingress:
            main:
              enabled: true
              annotations:
                hajimari.io/enable: "true"
                hajimari.io/icon: arcticons:paperless
                hajimari.io/info: Store PDFs
                hajimari.io/group: << inputs.hajimari_group >>
                nginx.ingress.kubernetes.io/proxy-body-size: 4G
                nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
                nginx.ingress.kubernetes.io/configuration-snippet: |
                  auth_request_set << inputs.auth_request_set >>;
              hosts:
                - host: << inputs.hostname >>
                  paths:
                    - path: /
                      pathType: Prefix
                      service:
                        identifier: main
                        port: http

