apiVersion: v1
kind: Secret
metadata:
    name: paperless-env-values
    #Password generate with https://generate.plus/en/base64
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:SKi0fuEJA9bWqDlGxcgtfz+OHAm8q78e8SC8DcwO+lZGYVMerJ9vplcv8kgM8UvVeWraZTFfaAp9gThtS1p9KQOuFWI/+v0DiEm8SHmPxO/aUm2cDCY=,iv:NZEX56WGxs8TZhOn7p4ZKB2QC8gX0aCiq+D3Xqariq4=,tag:DkMzoWGR9D++5zdko3N0zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbSsyYVdvcHFQVUxYRjho
            ZmpsZDU4QUE0NmpFb2hNdm42SXRESDMrT2hFCjM3TDZ4SGJJanFnZGVhdkNHdkQ1
            L2VsRmxnZE5mSithUlM5akZBTm8weG8KLS0tIGJkc2Y5Y2FQaFJqVXVva3FKSUNF
            aC9EQlFGWDg4cjNKR3NraktOczQySWMKou6x0MBSJ1rHpUlXyN+M6WFE5+fPBAOL
            amaKRxhI7J60Gx2HpwL8Lt/9mB9ADXr7wZ1wZCBkH3qryNGFWBSU1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDFZSStNd1p2Q0d4Y2JO
            RFo0ck1sUkNQQXFLL0VhdnhxKzdEc2VyWGs4ClVLMVVnQlFzcXVUWEtiYWpuT1JD
            aTFUcVJoMmhUMk5XWWx2R2xnWFNKdU0KLS0tIExDcXFvaEh6Unp0MHR3a1ozQmNt
            ajhsQ3hPYVR5NkJIdVRjaUg3NmpzODgKHk4kqUTWVQKIn9NnfCzK/oNl/h9sUWh4
            eM6gHNJXJo9Z8TD60jmNOkE5fP4N90+MLuTilXsMUOG5Er6V0q/jAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzljcFJ2TnZVSERXN1Jm
            NDk2QVcrYUJNMXgwTzdrRGgyS3lFMUdJZ3pRCk5MWTRaZVRYYzJFd01PYlBROU9q
            STNNQ3ZvWHJIMVZtSjAwc1NBWVYrSUkKLS0tIDFEdnVmd1Z5MmFiaEh0RmlESENM
            ZDZicW5ic0lYQnhkdnBUZ2NMc29zMEkKhudfqA15wJ++N6OAt5NNQoV+niv7Qk6O
            1BLlUIChWK719iqBnVrgolYcFGNR7SMsVJQh7JAabtt3EOwWX117+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmJHTTAydDc5UmJyUHZT
            NlU5QTZGVEphd283YlM5b2h3dzZrck9WSFFnClErWnlaS2ZMdjQ2QXRka01CalNF
            eHlYdER1ejloeVM1TktaL3dzNTd3UW8KLS0tIE9FSHlJOWtIZmxsTkszU3djN1ZS
            cWxDdDQ0cElDV2l2VE1nS0hyZTFKcGcK+sFPI9+b1FtqP3owvjJTU/QbTmlu4ymB
            O0HDMfUy2zc1Rxy7Y5CQhZTw/qlHZmDkM68FA+3wRRETnSQPFTjsOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-02T07:57:06Z"
    mac: ENC[AES256_GCM,data:ccqiPsOpFsDcMO0Xbmo0oSdKam1+s1AeOIeliZBA2FtZ6V1fJ10FE41e1uOWeSHxbQkUUiR/Kc+ox6pcFcIOHu/MLs2ekD8wbS/s9uf42AtgCnpGLk9H80E0y1hgofcOch5qZ9O2/VbWEtPMAtG+zKa8QBpDQ9CP3OkfqLS7EZI=,iv:m5Vz02lrPloYhEifToRhPW3HU2oYkUZ4FTbGj8Z7ZbM=,tag:uULRM7oelLs7McN1L+mJHg==,type:str]
    version: 3.13.3
