apiVersion: v1
kind: Secret
metadata:
    name: paperless-env-values
    #Password generate with https://generate.plus/en/base64
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:SKi0fuEJA9bWqDlGxcgtfz+OHAm8q78e8SC8DcwO+lZGYVMerJ9vplcv8kgM8UvVeWraZTFfaAp9gThtS1p9KQOuFWI/+v0DiEm8SHmPxO/aUm2cDCY=,iv:NZEX56WGxs8TZhOn7p4ZKB2QC8gX0aCiq+D3Xqariq4=,tag:DkMzoWGR9D++5zdko3N0zw==,type:str]
    #ENC[AES256_GCM,data:3zEFFnxkdgvJ8NhHZPEk+MtCeA==,iv:J8VKuZnp2KfMedz9iSLGeJDJ6U1+3qqLsAdDXu/Uugs=,tag:KwaP1n8V3jc6dzKR8NeJmw==,type:comment]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:YpOexK8=,iv:s4U2447016iVdre1JLzw8jvjtijCYYbNCK9MorNmiRo=,tag:6iAKi4HzRv9oNi5vDEGmnw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:qdIfEyMnM3WEDtJe6kY40WU9bro0nuCGaVO9LB0lO/W+yzcYoAwG5x/yE50xZX9ANki/cdkcCK0Fksmfrs4C5g==,iv:FGs324EAzEWUwhfa3IPCUXqZuFXHmP4HOR0mZ2l8QeE=,tag:QAPDLCNFbG+EEvkbX3U+sQ==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:Eu5FdykTrc9bXtTRsZFgU90=,iv:/lKMkTVtEWvF5Jj78nAOff1zOk6zPaGvZnX1VJfBga0=,tag:ERLXwqhwBYabFfGta+MDAw==,type:str]
    #ENC[AES256_GCM,data:dY9S1g==,iv:EnyQOy51GTXSWCieLLtQOXTdB0KzHoNsFMxJqYvyT4M=,tag:RrwAcnk2ajbMisbQm98M1w==,type:comment]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:E2jDo2VvsD0sGweuAlla194K+QnHxUa569n2EgskyT/aly8aFfdq87KoJLx7mr731JTr0EHl2ekkGgirP51GzcaJ2aKJ+LE/U68XmwoCXChTRHwdySCwyHnMsUhmzAGDDf7HfdF3AZCq85DWXeEaepHSlUnVChRwbEfUIaJUxhbJt0mWatj3t76K4flY7r/f/QT8g9iV3PoLihULJrXT/U4v6Wwlx0UWoUxbwg5BQ4ibZ+d19lNgg3l7rzpFGwYgHt5m9oBHxhZNLcGhwBTwtq3flUTB4bst5yz2znzDarJUHRBZ15DQinmCftZmK63855T7QOLbKSmpX+eQULoEHDiVVDaKpVwbCwsV2uBxJiaOmt1avmhmcG/IeAZ/ORo+Hb8qP9lZn9wnNEBwCK6uSmZNOAE3AIiHg6dQEusdxM9VinurvzqzFMzxjWLuS6DeqcsDqAzQOFnBFldaJFz5Jx6a/j4OV7GXD0A1D6BB/VPgtTmHBjiH8UDBJVtvrO9nvnzSkJKpmnX6oa4kIWVanlsDVQx3o3jnXXJreCig00uul3xgoEm4,iv:9hpNAgk3LoDM0icoawb2g6Ych8jrk7Ziw/L+mpsPrvs=,tag:Vd4oU1WOolnSfcUYuiaQCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbSsyYVdvcHFQVUxYRjho
            ZmpsZDU4QUE0NmpFb2hNdm42SXRESDMrT2hFCjM3TDZ4SGJJanFnZGVhdkNHdkQ1
            L2VsRmxnZE5mSithUlM5akZBTm8weG8KLS0tIGJkc2Y5Y2FQaFJqVXVva3FKSUNF
            aC9EQlFGWDg4cjNKR3NraktOczQySWMKou6x0MBSJ1rHpUlXyN+M6WFE5+fPBAOL
            amaKRxhI7J60Gx2HpwL8Lt/9mB9ADXr7wZ1wZCBkH3qryNGFWBSU1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDFZSStNd1p2Q0d4Y2JO
            RFo0ck1sUkNQQXFLL0VhdnhxKzdEc2VyWGs4ClVLMVVnQlFzcXVUWEtiYWpuT1JD
            aTFUcVJoMmhUMk5XWWx2R2xnWFNKdU0KLS0tIExDcXFvaEh6Unp0MHR3a1ozQmNt
            ajhsQ3hPYVR5NkJIdVRjaUg3NmpzODgKHk4kqUTWVQKIn9NnfCzK/oNl/h9sUWh4
            eM6gHNJXJo9Z8TD60jmNOkE5fP4N90+MLuTilXsMUOG5Er6V0q/jAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzljcFJ2TnZVSERXN1Jm
            NDk2QVcrYUJNMXgwTzdrRGgyS3lFMUdJZ3pRCk5MWTRaZVRYYzJFd01PYlBROU9q
            STNNQ3ZvWHJIMVZtSjAwc1NBWVYrSUkKLS0tIDFEdnVmd1Z5MmFiaEh0RmlESENM
            ZDZicW5ic0lYQnhkdnBUZ2NMc29zMEkKhudfqA15wJ++N6OAt5NNQoV+niv7Qk6O
            1BLlUIChWK719iqBnVrgolYcFGNR7SMsVJQh7JAabtt3EOwWX117+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmJHTTAydDc5UmJyUHZT
            NlU5QTZGVEphd283YlM5b2h3dzZrck9WSFFnClErWnlaS2ZMdjQ2QXRka01CalNF
            eHlYdER1ejloeVM1TktaL3dzNTd3UW8KLS0tIE9FSHlJOWtIZmxsTkszU3djN1ZS
            cWxDdDQ0cElDV2l2VE1nS0hyZTFKcGcK+sFPI9+b1FtqP3owvjJTU/QbTmlu4ymB
            O0HDMfUy2zc1Rxy7Y5CQhZTw/qlHZmDkM68FA+3wRRETnSQPFTjsOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-02T12:29:47Z"
    mac: ENC[AES256_GCM,data:+/xLutjTjen3y+ww3Jd4ZlsddYenvMpN0Pvd3z5KD9WYhmM0bD23YVaUiyWb8nPTp86+yNS5hvGnD3RYw43rknEcHMj81+NFQOB4Yi+2NUGlIeXuS/EjLb/qOxtx5W1ICbj6kTCf7dgKIRIBTv8+j0T808BZrNtxxJjFV+1QpbQ=,iv:pW8JhuzGCJx1AYgjoF0AtBLd2LZAc4z9lGmixdiury0=,tag:56rrijd7Puw+QZJiUutIww==,type:str]
    version: 3.13.3
