apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: Merge
spec:
  channel: stable-4.21
  desiredUpdate:
    image: registry.ci.openshift.org/origin/release-scos:4.22.0-okd-scos.0@sha256:018b65c9bd7fb045c7557e46665dacfa979ebe31d112c82b7c551ffe04e7f70f
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
