apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: Merge
spec:
  channel: stable-scos-4
  desiredUpdate:
    image: registry.ci.openshift.org/origin/release-scos:4.21.0-okd-scos.7@sha256:92d3f6d8c948ac41958f7613d48a52c7218a5a2ac2c3cb09e6ceb59b8fbb2894
  upstream: https://none.example.com # Disable automatic updates
