apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: Merge
spec:
  channel: stable-4.21
  desiredUpdate:
    image: registry.ci.openshift.org/origin/release-scos:4.21.0-okd-scos.11@sha256:4b930ee653c7e7671cf2d69e50a1898330556a09ac58b255fbe4b8addd53b290
  upstream: https://amd64.origin.releases.ci.openshift.org/graph
