apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-api-certs
  annotations:
    # This instructs Reflector to pull data from your source cert-manager secret
    reflector.v1.k8s.emberstack.com/reflects: "cert-manager/${CLUSTER_DOMAIN_CERT}" # Format: <source-namespace>/<source-secret-name>
type: Opaque
data: {}