---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: "${MY_APP}"
spec:
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  timeout: 20m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/library/alpine
              tag: latest@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
            command:
              - /bin/sh
              - -c
              - while true; do
                sleep 600 &
                wait $!;
                done
            resources:
              requests:
                memory: 10Mi
                cpu: 10m
              limits:
                memory: 500Mi
                cpu: 100m
        serviceAccount:
          identifier: default

    serviceAccount:
      default:
        enabled: true
    rbac:
      bindings:
        default:
          type: RoleBinding
          roleRef:
            name: system:openshift:scc:privileged # For network - TBD, try with less
            kind: ClusterRole
          subjects:
            - identifier: default
