---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-helm
spec:
  interval: 12h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    semver: "1.9.x"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-crds-helm
spec:
  interval: 12h
  url: oci://docker.io/envoyproxy/gateway-crds-helm
  ref:
    semver: "1.9.x"
