apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-values
    namespace: flux-system
stringData:
    values.yaml: ENC[AES256_GCM,data:PGz68vDHByd48AftWSB0L0M8jvrhnAUrj0UscXBjKwqQMTGJNKc5+ODlfJR3LVFKczL6gId48hUW8Igi7ce+6+lAnP/T0/5dx9/0ixAnXrE9XLuwqalIf5el9DzTVnHvIZUArkjjN8fpPNiWsKvpIQg1d2dCTOLqMCl9KawCIRH/emj3+Wjs20rUCslsPz84kkaQBQ==,iv:Gutz2D1ewaTjbcXyCzApWnRGaIwkwffMoVV4TT48UYI=,tag:1OQcafV1sW0kvx6ftzDSsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbSsyYVdvcHFQVUxYRjho
            ZmpsZDU4QUE0NmpFb2hNdm42SXRESDMrT2hFCjM3TDZ4SGJJanFnZGVhdkNHdkQ1
            L2VsRmxnZE5mSithUlM5akZBTm8weG8KLS0tIGJkc2Y5Y2FQaFJqVXVva3FKSUNF
            aC9EQlFGWDg4cjNKR3NraktOczQySWMKou6x0MBSJ1rHpUlXyN+M6WFE5+fPBAOL
            amaKRxhI7J60Gx2HpwL8Lt/9mB9ADXr7wZ1wZCBkH3qryNGFWBSU1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDFZSStNd1p2Q0d4Y2JO
            RFo0ck1sUkNQQXFLL0VhdnhxKzdEc2VyWGs4ClVLMVVnQlFzcXVUWEtiYWpuT1JD
            aTFUcVJoMmhUMk5XWWx2R2xnWFNKdU0KLS0tIExDcXFvaEh6Unp0MHR3a1ozQmNt
            ajhsQ3hPYVR5NkJIdVRjaUg3NmpzODgKHk4kqUTWVQKIn9NnfCzK/oNl/h9sUWh4
            eM6gHNJXJo9Z8TD60jmNOkE5fP4N90+MLuTilXsMUOG5Er6V0q/jAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzljcFJ2TnZVSERXN1Jm
            NDk2QVcrYUJNMXgwTzdrRGgyS3lFMUdJZ3pRCk5MWTRaZVRYYzJFd01PYlBROU9q
            STNNQ3ZvWHJIMVZtSjAwc1NBWVYrSUkKLS0tIDFEdnVmd1Z5MmFiaEh0RmlESENM
            ZDZicW5ic0lYQnhkdnBUZ2NMc29zMEkKhudfqA15wJ++N6OAt5NNQoV+niv7Qk6O
            1BLlUIChWK719iqBnVrgolYcFGNR7SMsVJQh7JAabtt3EOwWX117+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmJHTTAydDc5UmJyUHZT
            NlU5QTZGVEphd283YlM5b2h3dzZrck9WSFFnClErWnlaS2ZMdjQ2QXRka01CalNF
            eHlYdER1ejloeVM1TktaL3dzNTd3UW8KLS0tIE9FSHlJOWtIZmxsTkszU3djN1ZS
            cWxDdDQ0cElDV2l2VE1nS0hyZTFKcGcK+sFPI9+b1FtqP3owvjJTU/QbTmlu4ymB
            O0HDMfUy2zc1Rxy7Y5CQhZTw/qlHZmDkM68FA+3wRRETnSQPFTjsOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-30T10:45:54Z"
    mac: ENC[AES256_GCM,data:xyJnjBz9+CyENTmu27RHv0mZreWDFw3BPQC1wAoUAamwuTe3B+zQnAZcrhRqM6qAdx1awpuzfSCFYIEKw75L+4Osk+o34tgWoU7qB5d1kPIkmUzNh3+KEAoR6qCAM8Q9raSMNX2r1KQWC8o8VUyndKWPp1BIwGxdr+snc3vPoFM=,iv:q6w6pSelI46TWCysWKP8TNi+buR73/H9VqX2PiC7KlA=,tag:cp9brSC9kjXe9Ncq/C0m+w==,type:str]
    version: 3.13.1
