apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-values
    namespace: flux-system
stringData:
    values.yaml: ENC[AES256_GCM,data:QFdfg5XCKJNULCTbPt27tc/u7cBSxCczFrFngqndk50F460NxavG8IJrWUW7IzcWe8XsZbE1H3n2R3kZVS2P30QG16lXosnSDq7TDFjycKKwB/bo5DDQnp/ElZpT8CR306X2/qyEI4qGURY0yNmqhObNtUZ9vkIAF/CKpNOmvBNBk9PwHcxxTrDhepeDZDQwdKhVvMlCyrXmDChuz5snJg==,iv:KvXGpGX8OW9hme+LSRKTWLLUe4dHEAZQOLTqyNOTlvY=,tag:drAQY4WNN4wWqXNZASnqAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbSsyYVdvcHFQVUxYRjho
            ZmpsZDU4QUE0NmpFb2hNdm42SXRESDMrT2hFCjM3TDZ4SGJJanFnZGVhdkNHdkQ1
            L2VsRmxnZE5mSithUlM5akZBTm8weG8KLS0tIGJkc2Y5Y2FQaFJqVXVva3FKSUNF
            aC9EQlFGWDg4cjNKR3NraktOczQySWMKou6x0MBSJ1rHpUlXyN+M6WFE5+fPBAOL
            amaKRxhI7J60Gx2HpwL8Lt/9mB9ADXr7wZ1wZCBkH3qryNGFWBSU1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDFZSStNd1p2Q0d4Y2JO
            RFo0ck1sUkNQQXFLL0VhdnhxKzdEc2VyWGs4ClVLMVVnQlFzcXVUWEtiYWpuT1JD
            aTFUcVJoMmhUMk5XWWx2R2xnWFNKdU0KLS0tIExDcXFvaEh6Unp0MHR3a1ozQmNt
            ajhsQ3hPYVR5NkJIdVRjaUg3NmpzODgKHk4kqUTWVQKIn9NnfCzK/oNl/h9sUWh4
            eM6gHNJXJo9Z8TD60jmNOkE5fP4N90+MLuTilXsMUOG5Er6V0q/jAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzljcFJ2TnZVSERXN1Jm
            NDk2QVcrYUJNMXgwTzdrRGgyS3lFMUdJZ3pRCk5MWTRaZVRYYzJFd01PYlBROU9q
            STNNQ3ZvWHJIMVZtSjAwc1NBWVYrSUkKLS0tIDFEdnVmd1Z5MmFiaEh0RmlESENM
            ZDZicW5ic0lYQnhkdnBUZ2NMc29zMEkKhudfqA15wJ++N6OAt5NNQoV+niv7Qk6O
            1BLlUIChWK719iqBnVrgolYcFGNR7SMsVJQh7JAabtt3EOwWX117+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmJHTTAydDc5UmJyUHZT
            NlU5QTZGVEphd283YlM5b2h3dzZrck9WSFFnClErWnlaS2ZMdjQ2QXRka01CalNF
            eHlYdER1ejloeVM1TktaL3dzNTd3UW8KLS0tIE9FSHlJOWtIZmxsTkszU3djN1ZS
            cWxDdDQ0cElDV2l2VE1nS0hyZTFKcGcK+sFPI9+b1FtqP3owvjJTU/QbTmlu4ymB
            O0HDMfUy2zc1Rxy7Y5CQhZTw/qlHZmDkM68FA+3wRRETnSQPFTjsOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-30T19:56:05Z"
    mac: ENC[AES256_GCM,data:PknVrVDjGUO3PH2stfMe1ZX6r7jmAsHCLbBvAxK0YUSX58PCCwldFluWcqttlh4ldilLpRdpK66qyoxPDSueJoGujVOIgXbqEzqkLr9gSiv/KiJM/m/9PXi1mFCX5TiKOdWgaWZ1711Jg7ZYalQdloxsKNSpBh3v7s2mCebe1fE=,iv:q49YzJzUhJz+weeT3jLcBvDAjGfDw8Nn1snx2wpfk/k=,tag:nt9O7FQBT8LjRfs/H1u1QA==,type:str]
    version: 3.13.1
