apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-values
    namespace: flux-system
stringData:
    values.yaml: ENC[AES256_GCM,data:m1ANM4WcSu26lvBK/yrBend7IoY40U3Zn/pjh1LQg1NHLRUf4Ey1rDB/gzzbFdmTUZx9khV1j8TkXTTQlgM9HYd60NVfj97w73gokTfHfXYV+lquwoR8p4XuupYJCECH2gkN0JzydLZK2OyDg/1M878G36FvsRJz4UVoxtI/wDyStZ+GqprPnDZ7Cp3fUVdjDK+ZvwCFQWdvswQ8yur6,iv:DJPiupH3TNyfy5pG00vZYcqjvHS65DwCZSytRtPgee0=,tag:VS0JjvwDBDgy7lRioaYWeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbSsyYVdvcHFQVUxYRjho
            ZmpsZDU4QUE0NmpFb2hNdm42SXRESDMrT2hFCjM3TDZ4SGJJanFnZGVhdkNHdkQ1
            L2VsRmxnZE5mSithUlM5akZBTm8weG8KLS0tIGJkc2Y5Y2FQaFJqVXVva3FKSUNF
            aC9EQlFGWDg4cjNKR3NraktOczQySWMKou6x0MBSJ1rHpUlXyN+M6WFE5+fPBAOL
            amaKRxhI7J60Gx2HpwL8Lt/9mB9ADXr7wZ1wZCBkH3qryNGFWBSU1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDFZSStNd1p2Q0d4Y2JO
            RFo0ck1sUkNQQXFLL0VhdnhxKzdEc2VyWGs4ClVLMVVnQlFzcXVUWEtiYWpuT1JD
            aTFUcVJoMmhUMk5XWWx2R2xnWFNKdU0KLS0tIExDcXFvaEh6Unp0MHR3a1ozQmNt
            ajhsQ3hPYVR5NkJIdVRjaUg3NmpzODgKHk4kqUTWVQKIn9NnfCzK/oNl/h9sUWh4
            eM6gHNJXJo9Z8TD60jmNOkE5fP4N90+MLuTilXsMUOG5Er6V0q/jAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzljcFJ2TnZVSERXN1Jm
            NDk2QVcrYUJNMXgwTzdrRGgyS3lFMUdJZ3pRCk5MWTRaZVRYYzJFd01PYlBROU9q
            STNNQ3ZvWHJIMVZtSjAwc1NBWVYrSUkKLS0tIDFEdnVmd1Z5MmFiaEh0RmlESENM
            ZDZicW5ic0lYQnhkdnBUZ2NMc29zMEkKhudfqA15wJ++N6OAt5NNQoV+niv7Qk6O
            1BLlUIChWK719iqBnVrgolYcFGNR7SMsVJQh7JAabtt3EOwWX117+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmJHTTAydDc5UmJyUHZT
            NlU5QTZGVEphd283YlM5b2h3dzZrck9WSFFnClErWnlaS2ZMdjQ2QXRka01CalNF
            eHlYdER1ejloeVM1TktaL3dzNTd3UW8KLS0tIE9FSHlJOWtIZmxsTkszU3djN1ZS
            cWxDdDQ0cElDV2l2VE1nS0hyZTFKcGcK+sFPI9+b1FtqP3owvjJTU/QbTmlu4ymB
            O0HDMfUy2zc1Rxy7Y5CQhZTw/qlHZmDkM68FA+3wRRETnSQPFTjsOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krrdc5j8t9pf5qyldhgq59ayjktrkzs6kq730dpu4lpy6gkt9qqd8keur
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-30T11:13:25Z"
    mac: ENC[AES256_GCM,data:CWBljLpVKYBmdJl2mlBVKuRYjokn5ZER+5Rz5DBABHAonbw0NGmJtPvCjbIFnA8tHswpu8nXCSzyooVoFaXt0ao2wJRxaYfSoAG9EV7hxmj1oATjcF5TshDF9XkTZraTzXPugxhxQLry5m6SqBorgO8q4H5maUVZDLafEU1aLIQ=,iv:YfDYT4xNpY7EDUzCzWoVyq4ea3F64hmVq1Bl47p45Fw=,tag:fGoF8BiVvGAYu5kkkQf9fQ==,type:str]
    version: 3.13.1
